language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "fukakai"
    token:
      secure: "68F0YFyaG18K7LZWHiwAGA"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'